### PR TITLE
refraction_fix

### PR DESCRIPTION
**Pull request by Sisah2**
it fix refraction depth texture precision.

### CODE REVIEW

**Comment by xyzz** [comment]
I've no idea what this does or how to test it, can you explain?

**Comment by Sisah2** [comment]
You can test it if you enable water refraction, then use tcl command, fly above some water and look down while flying up. It also fix "wobbly water shores" which was added recently.
Here is one old video with this issue.
https://youtu.be/_bRjcI_bNLA
Recent changes broken it even more.

**Comment by Sisah2** [comment]
And here is picture how refraction texture looked on pc vs android
https://github.com/ptitSeb/gl4es/issues/328#issuecomment-892103463

**Comment by Sisah2** [comment]
Also unrelated thing, problem with shadows seems to be this
eyePlaneMat = mat4(gl_EyePlaneS[shadowTextureUnit@shadow_texture_unit_index], gl_EyePlaneT[shadowTextureUnit@shadow_texture_unit_index], gl_EyePlaneR[shadowTextureUnit@shadow_texture_unit_index], gl_EyePlaneQ[shadowTextureUnit@shadow_texture_unit_index]);
In shadows_vertex.glsl
Those eyePlane* functions always return 0.0
Then sampler 2d shadow is not supported, but using of that may be avoided.

**Pull request merged**
