### PR TITLE
Add bullet double precision support

### PR DESCRIPTION
**Pull request by terabyte25**
Do not merge this until https://github.com/OpenMW/openmw/pull/2049 is merged.

### CODE REVIEW

**Comment by xyzz** [comment]
Why only for 64-bit architectures?

**Comment by terabyte25** [comment]
@xyzz it is explained in the PR above. Apparently bullet's double precision only can support 64 bit archs.

**Comment by xyzz** [comment]
I don't see where it says that, in fact one of the last comments claims the opposite - https://github.com/OpenMW/openmw/pull/2049#issuecomment-482968482

Anyway, on Android we can use doubles everywhere except 32-bit x86, because we don't build for arm but for armv7 which supports them just fine https://developer.android.com/ndk/guides/abis#v7a

**Comment by xyzz** [comment]
Since there's not a lot of movement in the openmw regarding this I'll close it for now, feel free to reopen if/when openmw merges the required feature.

**Pull request closed without merging**
