### PR TITLE
Remove crashlytics from gradle

### PR DESCRIPTION
**Pull request by terabyte25**

### CODE REVIEW

**Comment by xyzz** [comment]
How's that a build flavor?

**Comment by terabyte25** [comment]
Whoops.

**Comment by licaon-kter** [comment]
Any news on a real flavour? I keep patching Crashlytics out as xyzz puts it in...but that's not a real longterm solution.

**Comment by terabyte25** [comment]
@licaon-kter what I was thinking to do is to use dummy class files with the same package name as the crashlytics and fabric libraries. However I do not know how to tell gradle to exclude those classes when building normally and include when building.

**Comment by licaon-kter** [comment]
I'll take a look at other project and try to grasp what's needed.

**Comment by terabyte25** [comment]
@licaon-kter You can look at [this commit.](https://github.com/jawg/osm-contributor/commit/c0702750de0c0869b5338e8b1993e900748d4b9a)

**Comment by terabyte25** [comment]
Or [this commit.](https://gitlab.ow2.org/RocketChat/Rocket.Chat.Android/commit/991580e02d2c3a091e94f8727b9431feb7343cd2)

**Comment by xyzz** [comment]
FYI I'm looking at replacing crashlytics with bugsnag and will likely provide a custom build flavor myself for disabling it.

**Comment by licaon-kter** [comment]
@xyzz Aren't Bugsnag's libs open source? If so, just add a settings toggle that we can just turn off (ya'know privacy) when we build and that's it.

Eg. https://github.com/AllanWang/Frost-for-Facebook

**Comment by terabyte25** [comment]
@licaon-kter yes, it is open-source, you can see the repository here https://github.com/bugsnag/bugsnag-android

**Comment by licaon-kter** [comment]
Great, no need to flavour this then. ;)

**Comment by xyzz** [comment]
Yep, it being free software is the reason for the switch. The flavor though is so that other people can build it without needing a bugsnag api key. Though I might drop the flavor idea and just add a runtime check for a valid api key or something.

**Comment by licaon-kter** [comment]
@xyzz yes, if there is no keyfile you can disable everything, or if allowed you'd include de key and get reports from F-Droid users willing to help.

**Comment by xyzz** [comment]
The problem with providing my api key is that it's gonna be two different applications (e.g. native binaries), so crashes from fdroid wouldn't get properly symbolized.

**Comment by licaon-kter** [comment]
@xyzz right right, ok, no file no bug reports :)

**Pull request closed without merging**
