### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Poussinou**
Hi,

This small PR adds links to get your app on F-Droid 👍

### CODE REVIEW

**Comment by licaon-kter** [comment]
No logos? :)

**Comment by Poussinou** [comment]
There is no logo for the different links to Google Play, I thought it was intentional from the developer to keep things like this.

By the way, I don't have any button with "nightly" written on it 😄

**Comment by licaon-kter** [comment]
Yeah, not special logos, plain :)

**Comment by Poussinou** [comment]
Well, let's keep everything like this

**Pull request merged**
