### PR TITLE
Always deploy assets

### PR DESCRIPTION
**Pull request by licaon-kter**
Fix https://github.com/OpenMW/android-port/issues/64

### CODE REVIEW

**Comment by xyzz** [comment]
The reason it's done this way is because I build arm64/x86-64/x86 in parallel in https://github.com/xyzz/openmw-android/blob/f36e6385c95473163624fedfc9bcd6d4145717a5/buildscripts/full-build.sh#L9

If every build tries to copy assets at the same time, there could be some nasty race condition? Either way, it's safer to require an arm build.

**Comment by terabyte25** [comment]
@xyzz Not quite, I've uncommented the conditional and have run the full build myriad times, but with no consequences.

**Comment by terabyte25** [comment]
@xyzz Not quite, I've uncommented the conditional and have run the full build myriad times, but with no consequences.

**Comment by xyzz** [comment]
That might be the case on linux and with current deploy that's just a cp, it doesn't mean there's no race condition.

**Comment by licaon-kter** [comment]
Yeah, saw that, I'll close since this was just an issue I've bumped into when building one version for speed reasons.

**Comment by xyzz** [comment]
FYI, this is now fixed (in a different way, but the same behavior) in https://github.com/xyzz/openmw-android/commit/6d1ca00be9041bb577f92cabdf7a83461f0bde10

**Pull request closed without merging**
